# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
